allow text to be piped to STDIN

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 
 # make sure yarn is installed
-command -v yarn >/dev/null 2>&1 || { echo "Could not find 'yarn', install that and re-run install.sh" >&2; exit 1; }
+command -v yarn >/dev/null 2>&1 || {
+	echo "Could not find 'yarn', install that and re-run install.sh" >&2
+	exit 1
+}
 
 # change to current dir
 cd "$(dirname ${BASH_SOURCE[0]})"
@@ -15,8 +18,8 @@ yarn install
 
 script_name="${cur_dir}/largechar"
 
-echo "#!/usr/bin/env sh" > "$script_name"
-cat "./help.sh" >> "$script_name"
-echo "yarn --cwd \"${cur_dir}\" start \"\$@\"" >> "$script_name"
+echo "#!/usr/bin/env bash" >"$script_name"
+cat "./help.sh" >>"$script_name"
+printf 'yarn --cwd "%s" start "${ARGS[@]}"\n' "$cur_dir" >>"$script_name"
 chmod +x "$script_name"
 echo "Copy ${script_name} to somewhere on your \$PATH"
