shellcheck improvements
double check to make sure something
was received from STDIN before running
electron

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,7 +7,10 @@ command -v yarn >/dev/null 2>&1 || {
 }
 
 # change to current dir
-cd "$(dirname ${BASH_SOURCE[0]})"
+if ! cd "$(dirname "${BASH_SOURCE[0]}")"; then
+	echo "Could not cd to the repo root directory" >&2
+	exit 1
+fi
 cur_dir="$(pwd)"
 
 # pull dependencies
@@ -20,6 +23,8 @@ script_name="${cur_dir}/largechar"
 
 echo '#!/usr/bin/env bash' >"${script_name}"
 cat ./help.bash >>"${script_name}"
+# shellcheck disable=SC2016
 printf 'yarn --cwd "%s" start "${ARGS[@]}"\n' "${cur_dir}" >>"${script_name}"
 chmod +x "${script_name}"
+# shellcheck disable=SC2016
 printf 'Copy %s to somewhere on your $PATH\n' "${script_name}"
