improve installer/shell script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,7 +2,7 @@
 
 # make sure yarn is installed
 command -v yarn >/dev/null 2>&1 || {
-	echo "Could not find 'yarn', install that and re-run install" >&2
+	echo 'Could not find yarn, install that and re-run install' >&2
 	exit 1
 }
 
@@ -18,8 +18,8 @@ yarn install
 
 script_name="${cur_dir}/largechar"
 
-echo "#!/usr/bin/env bash" >"$script_name"
-cat "./help.sh" >>"$script_name"
-printf 'yarn --cwd "%s" start "${ARGS[@]}"\n' "$cur_dir" >>"$script_name"
-chmod +x "$script_name"
-echo "Copy ${script_name} to somewhere on your \$PATH"
+echo '#!/usr/bin/env bash' >"${script_name}"
+cat ./help.bash >>"${script_name}"
+printf 'yarn --cwd "%s" start "${ARGS[@]}"\n' "${cur_dir}" >>"${script_name}"
+chmod +x "${script_name}"
+printf 'Copy %s to somewhere on your $PATH\n' "${script_name}"
